name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fanzru/antri-in-frontend:${{github.run_number}}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fanzru/antri-in-frontend
          tags: ${{ github.run_number }}, latest
